# base dependencies, enough to run the app server locally
db:
  image: mysql:5.6
  hostname: db
  domainname: example.com
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=localdevpwd
    - MYSQL_DATABASE=task
    - MYSQL_USER=task
    - MYSQL_PASSWORD=taskpwd