db:
  image: mysql:5.6
  hostname: db
  domainname: example.com
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=localdevpwd
    - MYSQL_DATABASE=task
    - MYSQL_USER=task
    - MYSQL_PASSWORD=taskpwd
app:
  image: com.example/spring-boot-docker-example:0.1.0
  hostname: app
  domainname: example.com
  links:
    - db
  ports:
    - "8080:8080"
  environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://db/task
    - SPRING_DATASOURCE_USERNAME=task
    - SPRING_DATASOURCE_PASSWORD=taskpwd
    - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.jdbc.Driver
